export const types = {
    CREATE_CAMPAIGN_REQUEST: 'CREATE_CAMPAIGN_REQUEST',
    CREATE_CAMPAIGN_SUCCESS: 'CREATE_CAMPAIGN_SUCCESS',
    CREATE_CAMPAIGN_FAILURE: 'CREATE_CAMPAIGN_FAILURE',

    GET_CAMPAIGN_REQUEST: 'GET_CAMPAIGN_REQUEST',
    GET_CAMPAIGN_SUCCESS: 'GET_CAMPAIGN_SUCCESS',
    GET_CAMPAIGN_FAILURE: 'GET_CAMPAIGN_FAILURE',

    GET_CAMPAIGNS_REQUEST: 'GET_CAMPAIGNS_REQUEST',
    GET_CAMPAIGNS_SUCCESS: 'GET_CAMPAIGNS_SUCCESS',
    GET_CAMPAIGNS_FAILURE: 'GET_CAMPAIGNS_FAILURE',
  }